### ISSUE TITLE
/api/jira/myself does not include groups

### ISSUE THREAD

**Issue by j-matus** [vacuumlabs/vlsso#5]
The response from `api/jira/myself` contains something like `"groups":{"size":4,"items":[]},` instead of a proper group list since the request is redirected to `{domain}.atlassian.net/api/rest/latest/{path}` without `?expand=groups`. The group list could be useful since it could be used to determine the user's rights. Could simply adding `?expand=groups` cause any issues? Is there another way to get the group list?

**Comment by michal-lenik** [comment]
@hleumas what do you think about the question above? Can we add `?expand=groups` to request to Jira? Or do you suggest other way? This will help integrate vlsso into EMS

**Comment by hleumas** [comment]
Do whatever works.

**Comment by j-matus** [comment]
Fixed in #9
